### ISSUE TITLE
Add "python"?

### ISSUE THREAD

**Issue by evertalbers** [danvk/ssi-server#6]
Running `./ssi_server` as mentioned in the doc did not work on my Mac, I did some Googling and found that I have to use something like `python ssi_server.py`. Probably a Python configuration issue on my Mac, but I don't know anything about Python, and I thought I'd let you know. More noobs might run into this.

Thanks for creating ssi-server, saves me lots of copy-pasting when building HTML prototypes!

**Comment by danvk** [comment]
The shebang line (`#!/usr/bin/env python`) means that these should do the same thing. So this is likely an issue with your Python setup.

Glad the server has helped you. You might want to take a look at [static site generators][1] like Jekyll. If I'd known about them in 2013 I probably wouldn't have written this!

[1]: https://www.staticgen.com/

**Comment by evertalbers** [comment]
The advantage of ssi-server over static site generators is that you only have to install a couple of minimal files and that you can transfer the whole project "as is" to any shared webhosting environment to show it to remote co-workers/clients. So it was no wasted time, if you ask me :-)
